### ISSUE TITLE
TypeError: WooCommerceRestApi is not a constructor

### ISSUE THREAD

**Issue by yonish3** [woocommerce/woocommerce-rest-api-js-lib#66]
I was using NPM [@woocommerce/woocommerce-rest-api ](https://www.npmjs.com/package/@woocommerce/woocommerce-rest-api) successfully to manage API requests to Woocommerce/ WP website.

Was using babel and CJS version:
`
const WooCommerceRestApi = require("@woocommerce/woocommerce-rest-api").default;

const api = new WooCommerceRestApi({
  url: "http://example.com",
  consumerKey: "ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  consumerSecret: "cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  version: "wc/v3"
});`

But since Node 14 is offering a simple way to use ESM I have added the following configuration to the package.json, so I can use the import statement: "type": "module"

So I should have been able to use this format:

`import WooCommerceRestApi from "@woocommerce/woocommerce-rest-api";

const api = new WooCommerceRestApi({
  url: "http://example.com",
  consumerKey: "ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  consumerSecret: "cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  version: "wc/v3"
});`

But now I get this error:

`file:///xxxxxx/test.js:5
const api = new WooCommerceRestApi({
            ^

TypeError: WooCommerceRestApi is not a constructor
    at file:///xxxxxxxx/test.js:5:13
    at ModuleJob.run (internal/modules/esm/module_job.js:138:23)
    at async Loader.import (internal/modules/esm/loader.js:178:24)`

Why would that happen?

**Comment by tomjn** [comment]
Does this work?

```js
import { WooCommerceRestApi } from "@woocommerce/woocommerce-rest-api";
```

**Comment by yonish3** [comment]
nop, but thanks anyway.
i gave up, will keep the old version

**Comment by jor3l** [comment]
workaround:
```
import wcapi from '@woocommerce/woocommerce-rest-api';
const { default: WooCommerceRestApi } = wcapi;
```

Not sure why it doesn't work but calling it like this does

**Comment by lukewarlow** [comment]
The reason it doesn't work is because of a missing section in package.json telling node which file to import, so it chooses the CJS code.
As a temporary fix change the import to explicitly choose the index.mjs file like below.

`import WooCommerceRestApi from "@woocommerce/woocommerce-rest-api/index.mjs"`

**Comment by robindelaater** [comment]
Wondering if there is a fix for this yet.. None of the workarounds seem to work for me.

**Comment by notmike101** [comment]
For anyone who comes here in the future looking for an solution to this error when using the ESM version, here's a solution that worked for me:

```javascript
import { default as WCAPI} from '@woocommerce/woocommerce-rest-api';

const { default: WooCommerceRestApi } = WCAPI;
```

From there, you can just use `WooCommerceRestApi` as described in the ESM example.

```javascript
const woocommerce = new WooCommerceRestApi({
  url: 'https://localhost',
  consumerKey: '',
  consumerSecret: '',
  version: 'wc/v3'
});
```

**Comment by tarpagad** [comment]
Didn't try all the solutions suggested here but here's another that worked for me:

```
import wc from "@woocommerce/woocommerce-rest-api";
const WooCommerceRestApi = wc.default;
```

**Comment by danaoairuike** [comment]
It's been 3 years. This issue is still not resolved.

**Comment by lukewarlow** [comment]
It's pretty clear this repository is effectively abandoned.
